Repository amahi/android, pull requests merged in 2020-06, with the labels that each got.

#458 Fix audio controller fragment and overlapping fragment
  src/main/java/org/amahi/anywhere/activity/ServerFilesActivity.java
  src/main/res/layout/activity_server_files.xml
Labels: bug, on hold

#533 Fix Translations in strings and keys
  src/main/java/org/amahi/anywhere/activity/ServerFilesActivity.java
  src/main/java/org/amahi/anywhere/adapter/AudioFilesAdapter.java
  src/main/java/org/amahi/anywhere/fragment/NavigationFragment.java
  src/main/java/org/amahi/anywhere/fragment/ServerFilesFragment.java
  src/main/java/org/amahi/anywhere/fragment/SettingsFragment.java
  src/main/java/org/amahi/anywhere/fragment/UploadSettingsFragment.java
  src/main/java/org/amahi/anywhere/server/ApiConnectionDetector.java
  src/main/java/org/amahi/anywhere/server/model/ServerFile.java
  src/main/java/org/amahi/anywhere/service/DownloadService.java
  src/main/java/org/amahi/anywhere/service/VideoService.java
  src/main/java/org/amahi/anywhere/tv/activity/MainTVActivity.java
  src/main/java/org/amahi/anywhere/tv/fragment/MainTVFragment.java
  src/main/java/org/amahi/anywhere/tv/fragment/ServerSelectFragment.java
  src/main/java/org/amahi/anywhere/tv/fragment/TvPlaybackAudioFragment.java
  src/main/java/org/amahi/anywhere/tv/fragment/TvPlaybackVideoFragment.java
  src/main/java/org/amahi/anywhere/tv/presenter/IconHeaderPresenter.java
  src/main/java/org/amahi/anywhere/tv/presenter/SettingsItemPresenter.java
  src/main/java/org/amahi/anywhere/util/Constants.java
  src/main/java/org/amahi/anywhere/util/Intents.java
  src/main/java/org/amahi/anywhere/util/Preferences.java
  src/main/java/org/amahi/anywhere/util/ProgressRequestBody.java
  src/main/res/values-hi-rIN/strings.xml
  src/main/res/values-ml-rIN/strings.xml
  src/main/res/values/strings.xml
Labels: bug, on hold

#539 Animation in RecyclerView
  src/main/java/org/amahi/anywhere/adapter/RecentFilesAdapter.java
  src/main/res/anim/recycler_list_anim.xml
  src/main/res/anim/recycler_list_item_anim.xml
  src/main/res/layout/activity_recent_files.xml
  src/main/res/layout/fragment_server_files.xml
Labels: duplicate, enhancement, on hold

#541 SearchView Layout Improvements
  src/main/java/org/amahi/anywhere/fragment/ServerFilesFragment.java
Labels: enhancement, on hold
