Repository amahi/android, pull requests merged in 2020-08, with the labels that each got.

#595 Added Enhanced Sorting of Files
  src/main/java/org/amahi/anywhere/bus/FileSortOptionClickEvent.java
  src/main/java/org/amahi/anywhere/fragment/FileSortOptionsDialogFragment.java
  src/main/java/org/amahi/anywhere/fragment/ServerFilesFragment.java
  src/main/java/org/amahi/anywhere/model/FileSortOption.java
  src/main/java/org/amahi/anywhere/util/Fragments.java
  src/main/java/org/amahi/anywhere/util/Preferences.java
  src/main/res/drawable/ic_check.xml
  src/main/res/drawable/ic_sort.xml
  src/main/res/layout/filesort_options_bottom_sheet.xml
  src/main/res/menu/action_bar_server_files.xml
Labels: able-to-merge, enhancement

#590 Added Google Playstore Rate This App Dialog Prompt
  README.md
  acra.properties.sample
  build.gradle
  fakeAcra.properties
  src/main/AndroidManifest.xml
  src/main/java/org/amahi/anywhere/AmahiApplication.java
  src/main/java/org/amahi/anywhere/activity/ServerFilesActivity.java
  src/main/java/org/amahi/anywhere/server/Api.java
  src/main/res/values-fr/strings.xml
  src/main/res/values/strings.xml
Labels: able-to-merge, enhancement

#594 Update Connection Error Conditions and User Experience in Apps
  src/main/java/org/amahi/anywhere/fragment/ServerAppsFragment.java
  src/main/res/layout/fragment_server_apps.xml
Labels: able-to-merge, enhancement

#535 Change Swipe Refresh in Navigation Fragment
  build.gradle
  src/main/java/org/amahi/anywhere/fragment/NavigationFragment.java
  src/main/java/org/amahi/anywhere/fragment/ServerFilesFragment.java
  src/main/java/org/amahi/anywhere/fragment/ServerSharesFragment.java
  src/main/java/org/amahi/anywhere/util/MultiSwipeRefreshLayout.java
  src/main/res/layout/fragment_navigation.xml
Labels: able-to-merge, enhancement

#592 Avoiding white-spaces in username
  src/main/java/org/amahi/anywhere/activity/AuthenticationActivity.java
Labels: bug

#598 Remove Fabric
  build.gradle
  src/main/java/org/amahi/anywhere/AmahiApplication.java
  src/main/java/org/amahi/anywhere/util/FileManager.java
Labels: enhancement

#601 File Options in Offline Files
  src/main/java/org/amahi/anywhere/fragment/FileOptionsDialogFragment.java
  src/main/java/org/amahi/anywhere/fragment/ServerFilesFragment.java
  src/main/java/org/amahi/anywhere/server/model/ServerFile.java
  src/main/java/org/amahi/anywhere/util/Fragments.java
Labels: bug

#602 Update SDK Version
  .travis.yml
  build.gradle
Labels: enhancement

#604 Added Update for ACRA
  build.gradle
Labels: enhancement

#610 Add onClick in Recent Files
  src/main/java/org/amahi/anywhere/adapter/RecentFilesAdapter.java
Labels: bug

#608 Added Materialized Icons for Upload Photos Activity
  src/main/res/drawable/ic_cellular_data.xml
  src/main/res/drawable/ic_location.xml
  src/main/res/drawable/ic_server.xml
  src/main/res/drawable/ic_share.xml
  src/main/res/drawable/ic_switch.xml
  src/main/res/drawable/ic_upload_location.xml
  src/main/res/values/strings.xml
  src/main/res/xml/upload_settings.xml
Labels: enhancement

#587 Added Scrollbar Feature
  src/main/res/layout/activity_offline_files.xml
  src/main/res/layout/activity_recent_files.xml
  src/main/res/layout/activity_server_files.xml
  src/main/res/layout/fragment_audio_list.xml
  src/main/res/layout/fragment_server_apps.xml
  src/main/res/layout/fragment_server_files.xml
  src/main/res/layout/fragment_server_shares.xml
Labels: enhancement

#617 Added increase in font size of Container Titles in Settings Screen/Activity
  src/main/res/menu/action_bar_navigation.xml
  src/main/res/values/strings.xml
Labels: enhancement

#609 Improvements to Background Services
  src/main/java/org/amahi/anywhere/AmahiApplication.java
  src/main/java/org/amahi/anywhere/AmahiModule.java
  src/main/java/org/amahi/anywhere/activity/NavigationActivity.java
  src/main/java/org/amahi/anywhere/activity/RecentFilesActivity.java
  src/main/java/org/amahi/anywhere/activity/ServerFileAudioActivity.java
  src/main/java/org/amahi/anywhere/activity/ServerFileVideoActivity.java
  src/main/java/org/amahi/anywhere/fragment/ServerFilesFragment.java
  src/main/java/org/amahi/anywhere/job/NetConnectivityJob.java
  src/main/java/org/amahi/anywhere/job/PhotosContentJob.java
  src/main/java/org/amahi/anywhere/receiver/CameraReceiver.java
  src/main/java/org/amahi/anywhere/receiver/NetworkReceiver.java
  src/main/java/org/amahi/anywhere/service/DownloadService.java
  src/main/java/org/amahi/anywhere/service/ServiceNotifier.java
  src/main/java/org/amahi/anywhere/service/UploadService.java
Labels: bug

#622 Fast Scroller
  build.gradle
  src/main/java/org/amahi/anywhere/activity/RecentFilesActivity.java
  src/main/java/org/amahi/anywhere/adapter/AudioFilesAdapter.java
  src/main/java/org/amahi/anywhere/adapter/FilesFilterAdapter.java
  src/main/java/org/amahi/anywhere/adapter/RecentFilesAdapter.java
  src/main/java/org/amahi/anywhere/adapter/ServerAppsAdapter.java
  src/main/java/org/amahi/anywhere/adapter/ServerFilesMetadataAdapter.java
  src/main/java/org/amahi/anywhere/adapter/ServerSharesAdapter.java
  src/main/java/org/amahi/anywhere/fragment/AudioListFragment.java
  src/main/java/org/amahi/anywhere/fragment/ServerAppsFragment.java
  src/main/java/org/amahi/anywhere/fragment/ServerFilesFragment.java
  src/main/java/org/amahi/anywhere/fragment/ServerSharesFragment.java
  src/main/res/layout/activity_offline_files.xml
  src/main/res/layout/activity_recent_files.xml
  src/main/res/layout/activity_server_files.xml
  src/main/res/layout/fragment_audio_list.xml
  src/main/res/layout/fragment_server_apps.xml
  src/main/res/layout/fragment_server_files.xml
  src/main/res/layout/fragment_server_shares.xml
  src/main/res/values/colors.xml
Labels: enhancement

#629 Add Server Switch loading
  src/main/java/org/amahi/anywhere/fragment/ServerSharesFragment.java
Labels: enhancement

#615 Update Strings in Preference Screen
  src/main/res/values-fr/strings.xml
Labels: enhancement

#621 Added Icons for Alert Dialogs
  src/main/java/org/amahi/anywhere/fragment/AlertDialogFragment.java
  src/main/res/drawable/ic_delete_dialog.xml
  src/main/res/drawable/ic_duplicate_dialog.xml
  src/main/res/drawable/ic_info_dialog.xml
Labels: enhancement, ui

#624 Added Amahi themed swipe refresh
  src/main/java/org/amahi/anywhere/fragment/ServerFilesFragment.java
  src/main/java/org/amahi/anywhere/fragment/ServerSharesFragment.java
Labels: enhancement, ui

#626 Fix TV mode support crash
  src/androidTest/java/org/amahi/anywhere/activity/AuthenticationActivityTest.java
  src/main/AndroidManifest.xml
  src/main/java/org/amahi/anywhere/adapter/FilesFilterAdapter.java
  src/main/java/org/amahi/anywhere/fragment/NavigationFragment.java
  src/main/java/org/amahi/anywhere/tv/activity/MainTVActivity.java
  src/main/java/org/amahi/anywhere/tv/presenter/IconHeaderPresenter.java
  src/main/java/org/amahi/anywhere/util/Constants.java
  src/main/java/org/amahi/anywhere/util/Intents.java
  src/main/res/values-fr/strings.xml
  src/main/res/values-hi-rIN/strings.xml
  src/main/res/values-ml-rIN/strings.xml
  src/main/res/values/strings.xml
Labels: bug, feat

#635 Update Version
  build.gradle
Labels: config

#634 Add Activity Callbacks
  src/main/java/org/amahi/anywhere/AmahiApplication.java
  src/main/java/org/amahi/anywhere/util/AmahiLifeCycleCallback.java
Labels: config

#636 Remove ACRA
  .gitignore
  README.md
  acra.properties.sample
  build.gradle
  fakeAcra.properties
  src/main/AndroidManifest.xml
  src/main/java/org/amahi/anywhere/AmahiApplication.java
  src/main/java/org/amahi/anywhere/server/Api.java
Labels: config

#642 Added Blue Color as Accent
  src/main/res/values-notnight/colors.xml
Labels: enhancement

#643 Added Update for Exoplayer
  build.gradle
Labels: enhancement

#648 Update Icon Files
  src/main/res/drawable/ic_brightness.xml
  src/main/res/drawable/ic_delete.xml
  src/main/res/drawable/ic_duplicate_dialog.xml
  src/main/res/drawable/ic_volume_up.xml
Labels: ui

#637 Added New Type of Loading Effect
  build.gradle
  src/main/res/layout/fragment_server_shares.xml
  src/main/res/layout/shares_loading.xml
  src/main/res/raw/loading_shares.json
Labels: enhancement

#641 Added Update for buildTools
  .travis.yml
  build.gradle
Labels: enhancement

#651 Remove Extra Drawables
  src/main/res/drawable-hdpi/bg_action_bar.9.png
  src/main/res/drawable-hdpi/ic_menu_sort_modification_time.png
  src/main/res/drawable-notnight-hdpi/ic_menu_sort_modification_time.png
  src/main/res/drawable-notnight-xhdpi/ic_menu_sort_modification_time.png
  src/main/res/drawable-notnight-xxhdpi/ic_menu_sort_modification_time.png
  src/main/res/drawable-notnight/ic_menu_sort_name.xml
  src/main/res/drawable-notnight/ic_menu_sort_size.xml
  src/main/res/drawable-xhdpi/bg_action_bar.9.png
  src/main/res/drawable-xhdpi/ic_menu_sort_modification_time.png
  src/main/res/drawable-xxhdpi/bg_action_bar.9.png
  src/main/res/drawable-xxhdpi/ic_menu_sort_modification_time.png
  src/main/res/drawable/divider.xml
  src/main/res/drawable/ic_location.xml
  src/main/res/drawable/ic_menu_sort_name.xml
  src/main/res/drawable/ic_menu_sort_size.xml
  src/main/res/drawable/ic_notification_audio.xml
  src/main/res/layout/container_files_dummy.xml
  src/main/res/values-w820dp/dimens.xml
  src/main/res/values/dimens.xml
Labels: ui/ux

#652 Added Espresso Update
  build.gradle
Labels: enhancement

#653 Added themed Files Sort indicator
  src/main/java/org/amahi/anywhere/fragment/FileSortOptionsDialogFragment.java
  src/main/res/drawable/ic_check.xml
Labels: enhancement

#655 Added themed Swipe refresh for Navigations and Server Apps Activity/Screen
  src/main/java/org/amahi/anywhere/fragment/NavigationFragment.java
  src/main/java/org/amahi/anywhere/fragment/ServerAppsFragment.java
Labels: enhancement

#656 Added Update for AndroidX Annotations
  build.gradle
Labels: enhancement

#657 Added themed Folder Icons
  src/main/res/values-notnight/colors.xml
  src/main/res/values/colors.xml
Labels: enhancement

#649 Linting
  src/main/AndroidManifest.xml
  src/main/java/org/amahi/anywhere/activity/RecentFilesActivity.java
  src/main/java/org/amahi/anywhere/activity/ServerFilesActivity.java
  src/main/java/org/amahi/anywhere/fragment/NavigationFragment.java
  src/main/java/org/amahi/anywhere/fragment/ServerSharesFragment.java
  src/main/java/org/amahi/anywhere/service/VideoService.java
  src/main/java/org/amahi/anywhere/tv/fragment/IntroFragment.java
  src/main/java/org/amahi/anywhere/tv/fragment/ServerSelectFragment.java
  src/main/java/org/amahi/anywhere/tv/presenter/IconHeaderPresenter.java
  src/main/java/org/amahi/anywhere/util/Android.java
  src/main/java/org/amahi/anywhere/util/Fragments.java
  src/main/java/org/amahi/anywhere/util/Intents.java
  src/main/java/org/amahi/anywhere/util/LocaleHelper.java
  src/main/java/org/amahi/anywhere/util/ProgressRequestBody.java
  src/main/java/org/amahi/anywhere/util/RecyclerItemClickListener.java
  src/main/java/org/amahi/anywhere/util/VideoSwipeGestures.java
  src/main/java/org/amahi/anywhere/view/TouchImageView.java
  src/main/res/layout/subtitles_surface.xml
  src/main/res/values-hi-rIN/strings.xml
  src/main/res/values-ml-rIN/strings.xml
  src/main/res/xml/searchable.xml
Labels: enhancement

#659 Added themed Scrollbar
  src/main/res/values/colors.xml
Labels: enhancement

#661 Added adaptive Login Stroke
  src/main/res/values/colors.xml
  src/main/res/values/themes.xml
Labels: enhancement

#650 Update Translations
  .github/ISSUE_TEMPLATE/pull-request.md
  src/main/java/org/amahi/anywhere/tv/fragment/TvPlaybackAudioFragment.java
  src/main/java/org/amahi/anywhere/tv/fragment/TvPlaybackVideoFragment.java
  src/main/res/values-es/strings.xml
  src/main/res/values-fr/strings.xml
  src/main/res/values-hi-rIN/strings.xml
  src/main/res/values-ml-rIN/strings.xml
  src/main/res/values/strings.xml
Labels: ui/ux
