Repository amahi/android, pull requests merged in 2020-07, with the labels that each got.

#440 fix: App crash after Sign out and Sign in again
  src/main/java/org/amahi/anywhere/fragment/NavigationFragment.java
Labels: bug, on hold

#501 Crash Solved Due to Storage and camera Permissions and Added Dialogue box
  build.gradle
  src/main/java/org/amahi/anywhere/activity/ServerFilesActivity.java
Labels: on hold

#504 FEAT: Music Player UI Enhanced
  src/main/java/org/amahi/anywhere/activity/ExpandedControlsActivity.java
  src/main/java/org/amahi/anywhere/activity/ServerFileAudioActivity.java
  src/main/java/org/amahi/anywhere/fragment/AudioControllerFragment.java
  src/main/java/org/amahi/anywhere/tv/fragment/TvPlaybackAudioFragment.java
  src/main/res/layout/activity_server_file_audio.xml
  src/main/res/layout/exo_player_control_view.xml
  src/main/res/layout/fragment_audio_controller.xml
Labels: enhancement, on hold

#545 Add Localization Support
  LANGUAGES.md
  src/main/java/org/amahi/anywhere/activity/AuthenticationActivity.java
  src/main/java/org/amahi/anywhere/activity/ExpandedControlsActivity.java
  src/main/java/org/amahi/anywhere/activity/IntroductionActivity.java
  src/main/java/org/amahi/anywhere/activity/NativeVideoActivity.java
  src/main/java/org/amahi/anywhere/activity/NavigationActivity.java
  src/main/java/org/amahi/anywhere/activity/OfflineFilesActivity.java
  src/main/java/org/amahi/anywhere/activity/RecentFilesActivity.java
  src/main/java/org/amahi/anywhere/activity/ServerAppActivity.java
  src/main/java/org/amahi/anywhere/activity/ServerFileAudioActivity.java
  src/main/java/org/amahi/anywhere/activity/ServerFileImageActivity.java
  src/main/java/org/amahi/anywhere/activity/ServerFileVideoActivity.java
  src/main/java/org/amahi/anywhere/activity/ServerFileWebActivity.java
  src/main/java/org/amahi/anywhere/activity/ServerFilesActivity.java
  src/main/java/org/amahi/anywhere/activity/SettingsActivity.java
  src/main/java/org/amahi/anywhere/activity/SplashActivity.java
  src/main/java/org/amahi/anywhere/activity/WebViewActivity.java
  src/main/java/org/amahi/anywhere/fragment/SettingsFragment.java
  src/main/java/org/amahi/anywhere/util/LocaleHelper.java
  src/main/res/values-fr/strings.xml
  src/main/res/values/preferences.xml
  src/main/res/values/strings.xml
  src/main/res/xml/settings.xml
Labels: on hold

#553 Fix: Inform user if there's no internet connection while trying to access media files
  build.gradle
  src/main/java/org/amahi/anywhere/activity/ServerFileVideoActivity.java
  src/main/java/org/amahi/anywhere/activity/ServerFilesActivity.java
  src/main/java/org/amahi/anywhere/fragment/ServerFileImageFragment.java
  src/main/java/org/amahi/anywhere/util/NetworkUtils.java
  src/main/res/values-fr/strings.xml
  src/main/res/values/strings.xml
Labels: on hold

#555 App Introduction Improvements
  src/main/java/org/amahi/anywhere/activity/IntroductionActivity.java
  src/main/java/org/amahi/anywhere/util/SampleSlide.java
  src/main/res/layout-land/intro_first_layout.xml
  src/main/res/layout/intro_first_layout.xml
  src/main/res/values-fr/strings.xml
  src/main/res/values/strings.xml
Labels: on hold

#561 [Fix] App Not Loading
  src/main/java/org/amahi/anywhere/activity/ServerAppActivity.java
Labels: able-to-merge

#562 Add release to gitignore
  .gitignore
Labels: able-to-merge, enhancement

#568 Update README with better badges
  README.md
Labels: able-to-merge

#565 Application Crash Reports
  .gitignore
  .travis.yml
  README.md
  acra.properties.sample
  build.gradle
  fakeAcra.properties
  fakeApi.properties
  fakeSigning.properties
  gradle/wrapper/gradle-wrapper.properties
  src/main/AndroidManifest.xml
  src/main/java/org/amahi/anywhere/AmahiApplication.java
  src/main/java/org/amahi/anywhere/server/Api.java
  src/main/res/values/strings.xml
Labels: able-to-merge

#574 Added Last Opened Display of Files Feature
  src/main/java/org/amahi/anywhere/activity/ServerFileAudioActivity.java
  src/main/java/org/amahi/anywhere/activity/ServerFileImageActivity.java
  src/main/java/org/amahi/anywhere/activity/ServerFileVideoActivity.java
  src/main/java/org/amahi/anywhere/activity/ServerFileWebActivity.java
  src/main/java/org/amahi/anywhere/bus/FileOptionClickEvent.java
  src/main/java/org/amahi/anywhere/db/AppDatabase.java
  src/main/java/org/amahi/anywhere/db/daos/FileInfoDao.java
  src/main/java/org/amahi/anywhere/db/entities/FileInfo.java
  src/main/java/org/amahi/anywhere/db/repositories/FileInfoRepository.java
  src/main/java/org/amahi/anywhere/fragment/AlertDialogFragment.java
  src/main/java/org/amahi/anywhere/fragment/FileOptionsDialogFragment.java
  src/main/java/org/amahi/anywhere/fragment/ServerFilesFragment.java
  src/main/java/org/amahi/anywhere/model/FileOption.java
  src/main/java/org/amahi/anywhere/util/DateTime.java
  src/main/java/org/amahi/anywhere/util/Fragments.java
  src/main/res/drawable/ic_info_outline.xml
  src/main/res/layout/bottom_sheet_options.xml
  src/main/res/layout/file_info_dialog.xml
  src/main/res/values/strings.xml
Labels: able-to-merge, enhancement

#580 Added Updates to libraries
  build.gradle
Labels: able-to-merge, enhancement

#576 Add Repeat and Shuffle Feature to Music Player
  build.gradle
  src/main/java/org/amahi/anywhere/activity/ServerFileAudioActivity.java
  src/main/java/org/amahi/anywhere/service/AudioService.java
  src/main/java/org/amahi/anywhere/util/Preferences.java
  src/main/res/layout/activity_server_file_audio.xml
  src/main/res/layout/exo_player_control_view.xml
Labels: able-to-merge, enhancement

#573 Add Custom Tabs to WebView
  src/main/java/org/amahi/anywhere/AmahiModule.java
  src/main/java/org/amahi/anywhere/activity/ServerFileWebActivity.java
  src/main/java/org/amahi/anywhere/activity/WebViewActivity.java
  src/main/java/org/amahi/anywhere/util/Constants.java
  src/main/res/layout/activity_server_file_web.xml
  src/main/res/layout/activity_web_view.xml
Labels: able-to-merge, enhancement

#578 Update Travis Configuration
  .travis.yml
Labels: able-to-merge

#581 Update gitignore to include jks and keystore
  .gitignore
Labels: able-to-merge
