Repository amahi/android, pull requests merged in 2020-12, with the labels that each got.

#678 Added Improved Files Sort Bottom Sheet
  src/main/res/layout/filesort_options_bottom_sheet.xml
  src/main/res/values/strings.xml
Labels: enhancement, ui/ux

#689 Replaced switch with if/else statements for Non-Constant Fields in Ca…
  src/main/java/org/amahi/anywhere/activity/NativeVideoActivity.java
  src/main/java/org/amahi/anywhere/activity/OfflineFilesActivity.java
  src/main/java/org/amahi/anywhere/activity/RecentFilesActivity.java
  src/main/java/org/amahi/anywhere/activity/ServerAppActivity.java
  src/main/java/org/amahi/anywhere/activity/ServerFileAudioActivity.java
  src/main/java/org/amahi/anywhere/activity/ServerFileImageActivity.java
  src/main/java/org/amahi/anywhere/activity/ServerFileVideoActivity.java
  src/main/java/org/amahi/anywhere/activity/ServerFilesActivity.java
  src/main/java/org/amahi/anywhere/activity/SettingsActivity.java
  src/main/java/org/amahi/anywhere/fragment/NavigationFragment.java
  src/main/java/org/amahi/anywhere/fragment/ServerFilesFragment.java
Labels: enhancement

#690 Grammar correction in strings.xml
  src/main/res/values/strings.xml
Labels: ui/ux

#691 German language added
  src/main/res/values-bn/strings.xml
  src/main/res/values-de/strings.xml
  src/main/res/values-es/strings.xml
  src/main/res/values-fr/strings.xml
  src/main/res/values/strings.xml
Labels: ui/ux

#695 Added adaptive icons for Android 8.0 and above
  src/main/AndroidManifest.xml
  src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  src/main/res/mipmap-hdpi/ic_launcher.png
  src/main/res/mipmap-hdpi/ic_launcher_foreground.png
  src/main/res/mipmap-mdpi/ic_launcher.png
  src/main/res/mipmap-mdpi/ic_launcher_foreground.png
  src/main/res/mipmap-xhdpi/ic_launcher.png
  src/main/res/mipmap-xhdpi/ic_launcher_foreground.png
  src/main/res/mipmap-xxhdpi/ic_launcher.png
  src/main/res/mipmap-xxhdpi/ic_launcher_foreground.png
  src/main/res/mipmap-xxxhdpi/ic_launcher.png
  src/main/res/mipmap-xxxhdpi/ic_launcher_foreground.png
  src/main/res/values/ic_launcher_background.xml
Labels: ui/ux
