Repository amahi/android, pull requests merged in 2020-09, with the labels that each got.

#658 Added FFmpegMediaMetadataRetriever Library Update
  build.gradle
Labels: enhancement

#663 Add cast icon
  src/main/res/drawable/ic_cast.xml
  src/main/res/menu/action_bar_audio_files.xml
  src/main/res/menu/action_bar_cast_button.xml
  src/main/res/menu/action_bar_server_file_image.xml
  src/main/res/menu/action_bar_server_files.xml
  src/main/res/menu/action_bar_video_files.xml
Labels: ui/ux

#664 Correct landscape view in file options and files sorting
  src/main/java/org/amahi/anywhere/fragment/FileOptionsDialogFragment.java
  src/main/java/org/amahi/anywhere/fragment/FileSortOptionsDialogFragment.java
  src/main/res/layout/bottom_sheet_options.xml
  src/main/res/layout/filesort_options_bottom_sheet.xml
  src/main/res/values-es/strings.xml
  src/main/res/values-fr/strings.xml
  src/main/res/values/strings.xml
Labels: bug, ui/ux

#667 Added Dancing Dots loading for Server Files Activity/Screen
  src/main/res/layout/fragment_server_files.xml
Labels: enhancement

#671 Added Update for Play Services Cast framework
  build.gradle
Labels: enhancement

#675 Bengali(bn, Indian language) new language added
  src/main/res/values-bn/strings.xml
  src/main/res/values-es/strings.xml
  src/main/res/values-fr/strings.xml
  src/main/res/values/strings.xml
Labels: ui/ux

#654 Added test runner and test rules update
  build.gradle
Labels: enhancement
