Repository amahi/android, pull requests merged in 2021-02, with the labels that each got.

#684 Added Translations for Punjabi Language
  src/main/res/values-bn/strings.xml
  src/main/res/values-es/strings.xml
  src/main/res/values-fr/strings.xml
  src/main/res/values-pa/strings.xml
  src/main/res/values-te/strings.xml
  src/main/res/values/strings.xml
Labels: ui/ux

#668 Added update for archRoomVersion
  build.gradle
Labels: enhancement

#693 Corrected color of up arrow in Settings Activity and removed unnecessary…
  src/main/java/org/amahi/anywhere/activity/SettingsActivity.java
  src/main/res/drawable/arrow_back.xml
  src/main/res/drawable/ic_cellular_data.xml
  src/main/res/drawable/ic_server.xml
  src/main/res/drawable/ic_settings_translate.xml
  src/main/res/drawable/ic_share.xml
  src/main/res/drawable/ic_sort.xml
  src/main/res/drawable/ic_switch.xml
  src/main/res/drawable/ic_upload_location.xml
  src/main/res/values/themes.xml
Labels: enhancement

#704 Corrected Hindi translations and added Copyright.
  src/main/res/values-bn/strings.xml
  src/main/res/values-hi/strings.xml
  src/main/res/values-te/strings.xml
Labels: enhancement, ui/ux

#706 Updated target SDK and compile SDK version
  .travis.yml
  build.gradle
Labels: enhancement

#707 Removed outdated code which were for Android SDK version lower than 21
  src/main/java/org/amahi/anywhere/tv/fragment/SignOutFragment.java
  src/main/java/org/amahi/anywhere/tv/fragment/TvPlaybackAudioFragment.java
  src/main/java/org/amahi/anywhere/tv/fragment/TvPlaybackVideoFragment.java
  src/main/java/org/amahi/anywhere/util/Android.java
  src/main/java/org/amahi/anywhere/util/PathUtil.java
  src/main/res/layout-v21/view_server_file_item.xml
  src/main/res/layout/view_server_file_item.xml
  src/main/res/values-v21/themes.xml
  src/main/res/values/themes.xml
Labels: enhancement

#711 Improved textStyle of File Sort Options
  src/main/res/layout/filesort_options_bottom_sheet.xml
Labels: ui/ux

#714 Changed Highlight color to Accent Color while Searching
  src/main/java/org/amahi/anywhere/adapter/FilesFilterAdapter.java
  src/main/java/org/amahi/anywhere/adapter/ServerFilesAdapter.java
  src/main/java/org/amahi/anywhere/adapter/ServerFilesMetadataAdapter.java
Labels: ui/ux

#716 Fixed Language Not Changing Bug
  build.gradle
Labels: bug

#718 Addition of github actions
  .github/workflows/build.yaml
  .travis.yml
Labels: enhancement

#747 GitHub action for merge conflict notification
  .github/workflows/build.yaml
  .github/workflows/conflict.yaml
Labels: config
